### PR TITLE
 feat(http): add retriable client; log response body on error

### PR DESCRIPTION
**Pull request by moleus**

### CODE REVIEW

**Comment by twocolors** [comment]
@Moleus sorry write in pull, can you open issues for this repo?

**Comment by moleus** [comment]
Hi! Sorry, but it's a fork, thats why issues can't be created at this repo. It's the restriction of GitHub. 

I can create new repo (not a fork) of this project. If @ad is okey with that

**Comment by ad** [comment]
I can unarchive repo if you need. But I don't have domru account at that moment.

**Comment by twocolors** [comment]
you can enable in setting issues

**Comment by moleus** [comment]
@twocolors you are right! Enabled in settings

**Pull request closed without merging**
