### PR TITLE
fix: show more one camera in intercom

### PR DESCRIPTION
**Pull request by twocolors**
hi, i have more one camera (AccessControls) in intercom (https://github.com/ad/domru/issues/9) and this pull fix show cameras in web

### CODE REVIEW

**Comment by moleus** [comment]
Thank you! I'll take a look in a few days and merge the PR

**Comment by moleus** [comment]
And I've just noticed that build doesn't run on a feature branch. I'll fix it, so we can test an image before merfing

**Comment by moleus** [comment]
@twocolors  Now CI builds docker image on each PR, can you merge dev into your branch?

**Comment by moleus** [comment]
I've built the image from this branch, you can it here - https://github.com/moleus/domru/pkgs/container/domru/213889326?tag=devel-more-cameras

I don't have multiple AccessControls per place so can't see the difference, but you can try. If everything is working as expected for you I'll merge it

**Comment by twocolors** [comment]
work
domru

**Pull request merged**
